"""One-shot: split the monolithic game/vibe-map.html into src/.

Run once against the 2026-09-16 build (1708 lines). Line ranges are exact so
that tools/build.py reproduces the original byte for byte; afterwards src/ is
the source and this script is history. Kept so the split is reproducible.

    uv run python tools/split_game.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GAME = ROOT / "game" / "vibe-map.html"
SRC = ROOT / "src"

# (file, first line, last line), 1-based inclusive, contiguous over 654..1704
GAME_MODULES = [
    ("00-state.js", 654, 693),
    ("10-scene.js", 694, 706),
    ("11-character.js", 707, 741),
    ("12-buildings.js", 742, 772),
    # 773-774: CAMPAIGN and MENTORS, moved to src/data/campaign.json
    ("20-worlds.js", 775, 811),
    ("21-world-build.js", 812, 922),
    ("30-input.js", 923, 943),
    ("31-animate.js", 944, 1032),
    ("40-sheet.js", 1033, 1074),
    # 1075: `const NOTES={`, 1076..: generated tech notes, then handwritten
    # notes to 1601 `};`. The generated block is injected by the build.
    ("50-notes.js", None, 1601),
    ("51-notes-dynamic.js", 1602, 1610),
    # 1611: AGES and TREE, generated by tools/regen_tree.py
    ("60-vault.js", 1612, 1667),
    ("70-minigames.js", 1668, 1690),
    ("71-finale.js", 1691, 1698),
    ("80-sync.js", 1699, 1702),
    ("90-boot.js", 1703, 1704),
]


def _lines(a: int, b: int, lines: list[str]) -> str:
    return "\n".join(lines[a - 1 : b]) + "\n"


def main() -> None:
    text = GAME.read_text(encoding="utf-8")
    lines = text.split("\n")
    assert len(lines) == 1708, f"expected the 1708-line build, got {len(lines)}"
    assert lines[652] == "(function(){" and lines[1704] == "})();"
    assert lines[1707] == "</html>", "the build has no trailing newline"
    (SRC / "game").mkdir(parents=True, exist_ok=True)
    (SRC / "vendor").mkdir(exist_ok=True)
    (SRC / "data").mkdir(exist_ok=True)

    (SRC / "head.html").write_text(_lines(1, 8, lines))
    (SRC / "style.css").write_text(_lines(10, 166, lines))
    (SRC / "body.html").write_text(_lines(169, 641, lines))
    err = lines[641]
    assert err.startswith("<script>") and err.endswith("</script>")
    (SRC / "errors.js").write_text(err[len("<script>") : -len("</script>")] + "\n")
    (SRC / "vendor" / "three.min.js").write_text(_lines(644, 650, lines))

    campaign = json.loads(lines[772][len("const CAMPAIGN=") : -1])
    mentors = json.loads(lines[773][len("const MENTORS=") : -1])
    (SRC / "data" / "campaign.json").write_text(
        json.dumps(
            {"evenings": campaign, "mentors": mentors}, indent=1, ensure_ascii=False
        )
        + "\n"
    )

    gen = (ROOT / "tools" / "generated" / "notes.js").read_text(encoding="utf-8")
    notes_region = _lines(1076, 1601, lines)
    assert notes_region.startswith(gen), "generated notes must open the NOTES literal"
    handwritten = notes_region[len(gen) :]
    assert handwritten.startswith(",\n"), repr(handwritten[:40])
    (SRC / "game" / "50-notes.js").write_text(handwritten[2:])

    for name, a, b in GAME_MODULES:
        if a is None:
            continue
        (SRC / "game" / name).write_text(_lines(a, b, lines))
    assert lines[1610] == (ROOT / "tools" / "generated" / "tree.js").read_text().rstrip(
        "\n"
    )

    listing = sorted(
        p.relative_to(SRC).as_posix() for p in SRC.rglob("*") if p.is_file()
    )
    print("\n".join(listing))
    print(f"{len(listing)} files written to src/")
    assert chr(0x2014) not in text[: text.find("<script>")], "em dash in markup"


if __name__ == "__main__":
    main()
